name: watch

on:
  schedule:
    # Every 1 hour
    - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: oven-sh/setup-bun@main
        with:
          bun-version: latest
          bun-download-url: "https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64.zip"

      - name: Watch
        run: bun i -f
      - run: bun src/watch.ts
